version: "3.0"
services:
  app:
    restart: always
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - common_data:/usr/src/app/static
    env_file: .env
    command: bash -c "cd /usr/src && APP_SETTING=.env python -m app.server"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    depends_on:
      - frontend
      - app
    env_file: .env

  frontend:
    restart: always
    build: ./frontend/
    depends_on:
      - app
      
volumes:
  common_data:
